{% set version = "3.9.5.0" %}

package:
  name: gnuradio
  version: {{ version }}

source:
  url: https://github.com/gnuradio/gnuradio/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 066c88fcf05046593e534416a3526ee433c3b90a7faa40fca914add23989ef3e
  patches:
    - 0001-cmake-Install-python-wrapper-exe-for-scripts-on-Wind.patch
    - 0002-cmake-Don-t-generate-.pyc-and-.pyo-files.patch
    - 0003-Use-an-ImageSurface-rather-than-UI-back-end.patch  # [osx]
    - 0004-grc-Remove-global_blocks_path-preference-and-use-pre.patch

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake >=3.8
    - ninja
    - patch  # [osx]
    - pkg-config  # [not win]
    - thrift-compiler  # [not win]
    # cross-compilation requirements
    - python                              # [build_platform != target_platform]
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - pybind11                            # [build_platform != target_platform]
    - numpy                               # [build_platform != target_platform]
    # libudev CDT needed to link against libusb through uhd on linux CentOS 6
    # libusb uses the conda-forge libudev package for CentOS 7
    - {{ cdt('libudev-devel') }}  # [linux and cdt_name=='cos6']
    # below are needed to link with Qt for qtgui
    - {{ cdt('libice') }}  # [linux and not ppc64le]
    - {{ cdt('libselinux') }}  # [linux and not ppc64le]
    - {{ cdt('libsm') }}  # [linux and not ppc64le]
    - {{ cdt('libx11') }}  # [linux and not ppc64le]
    - {{ cdt('libxau') }}  # [linux and not ppc64le]
    - {{ cdt('libxcb') }}  # [linux and not ppc64le]
    - {{ cdt('libxdamage') }}  # [linux and not ppc64le]
    - {{ cdt('libxext') }}  # [linux and not ppc64le]
    - {{ cdt('libxfixes') }}  # [linux and not ppc64le]
    - {{ cdt('libxrender') }}  # [linux and not ppc64le]
    - {{ cdt('libxxf86vm') }}  # [linux and not ppc64le]
    - {{ cdt('libuuid') }}  # [linux and not ppc64le]
    - {{ cdt('mesa-dri-drivers') }}  # [linux and not ppc64le]
    - {{ cdt('mesa-libgl-devel') }}  # [linux and not ppc64le]

  host:
    - boost-cpp
    - click
    - click-plugins
    - codec2
    - fftw
    - gmp  # [not win]
    - gsl
    # blas needed to link with gsl
    - libcblas  # [linux]
    - libsndfile
    - libthrift  # [not win]
    # restrict to cos6-compatible libusb (and libudev)
    - libusb-cos6  # [linux and cdt_name=='cos6']
    - log4cpp
    - mako
    - mpir  # [win]
    - numpy
    - pip  # [win]
    - pybind11
    - pybind11-abi
    - python
    - six
    - thrift  # [not win]
    - volk
  # gnuradio.audio
    - alsa-lib  # [linux]
    - portaudio
  # gnuradio companion
    - gtk3
    - lxml
    - pygobject
    - pyyaml
  # gnuradio.qtgui
    - pyqt  # [not (ppc64le or arm64)]
    - qt  # [not (ppc64le or arm64)]
    - qwt  # [not (ppc64le or arm64)]
  # gnuradio soapy
    - soapysdr
  # gnuradio.uhd
    - uhd
  # gnuradio.video_sdl
    - sdl
  # gnuradio.zeromq
    - cppzmq
    - zeromq

  run:
  # this is the metapackage that depends on all the subpackages
    - {{ pin_subpackage('gnuradio-core', exact=True) }}
    - {{ pin_subpackage('gnuradio-grc', exact=True) }}
    - {{ pin_subpackage('gnuradio-qtgui', exact=True) }}  # [not (ppc64le or arm64)]
    - {{ pin_subpackage('gnuradio-soapy', exact=True) }}
    - {{ pin_subpackage('gnuradio-uhd', exact=True) }}
    - {{ pin_subpackage('gnuradio-video-sdl', exact=True) }}
    - {{ pin_subpackage('gnuradio-zeromq', exact=True) }}
  # explicitly add python so that build string is generated correctly
    - python

test:
  downstreams:
    - gnuradio-osmosdr
    - gnuradio-satellites
  requires:
    - sqlite
  imports:
    - gnuradio.gr
    - gnuradio.qtgui  # [not (ppc64le or arm64)]
    - gnuradio.soapy
    - gnuradio.uhd
    - gnuradio.video_sdl
    - gnuradio.zeromq

app:
  entry: gnuradio-companion
  icon: grc-icon.png
  summary: GNU Radio Companion

outputs:
  - name: gnuradio-core
    script: install_core.sh  # [not win]
    script: install_core.bat  # [win]
    build:
      entry_points:
        - gr_filter_design = gnuradio.filter.filter_design:main  # [win]
        - gr_modtool = gnuradio.modtool.cli.base:cli  # [win]
      run_exports:
        - {{ pin_subpackage('gnuradio-core', max_pin='x.x.x') }}
        # log4cpp is used in block headers, so everything compiling against
        # gnuradio-core will almost-definitely need log4cpp at runtime
        - {{ pin_compatible('log4cpp', max_pin='x.x') }}
      skip_compile_pyc:
        - "*/templates/*.py"
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        # conda-build needs native python to make .pyc files
        - python  # [build_platform != target_platform]
      host:
        - alsa-lib  # [linux]
        - boost-cpp
        - codec2
        - fftw
        - gmp  # [not win]
        - gsl
        - libcblas  # [linux]
        - libsndfile
        - libthrift  # [not win]
        - log4cpp
        - mpir  # [win]
        - portaudio
        - pybind11
        - pybind11-abi
        - python
        - numpy
        - thrift  # [not win]
        - volk
      run:
        - boost-cpp
        - click
        - click-plugins
        - fftw
        - mako
        - menuinst  # [win]
        - numpy
        - {{ pin_compatible('portaudio') }}
        - python
        - pyyaml
        # need setuptools because modtool uses pkg_resources
        - setuptools
        - six
        - thrift  # [not win]
    test:
      commands:
        - gnuradio-config-info -v --prefix --sysconfdir --prefsdir --userprefsdir --prefs --builddate --enabled-components --cc --cxx --cflags
        - gr_modtool --help
        - if not exist %PREFIX%\\Scripts\\gr_filter_design.exe exit 1  # [win]
        - if not exist %PREFIX%\\Scripts\\gr_modtool.exe exit 1  # [win]
      imports:
        - gnuradio.analog
        - gnuradio.audio
        - gnuradio.blocks
        - gnuradio.channels
        - gnuradio.digital
        - gnuradio.dtv
        - gnuradio.fec
        - gnuradio.fft
        - gnuradio.filter
        - gnuradio.gr
        - gnuradio.network
        - gnuradio.trellis
        - gnuradio.vocoder
        - gnuradio.wavelet
        - pmt
    about:
      home: https://gnuradio.org/
      doc_url: https://gnuradio.org/doc/doxygen/
      dev_url: https://github.com/gnuradio/gnuradio
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: GNU Radio core functionality and modules
  - name: gnuradio-grc
    script: install_grc.sh  # [not win]
    script: install_grc.bat  # [win]
    build:
      entry_points:
        - gnuradio-companion = gnuradio.grc.main:main  # [win]
        - grcc = gnuradio.grc.compiler:main  # [win]
      ignore_run_exports_from:
        # workaround to get host environment solved
        - openssl
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        # conda-build needs native python to make .pyc files
        - python  # [build_platform != target_platform]
      host:
        - boost-cpp
        - {{ pin_subpackage('gnuradio-core', exact=True) }}
        - gtk3
        - log4cpp
        # workaround to get host environment solved
        - openssl
        - python
      run:
        - boost-cpp
        - {{ pin_subpackage('gnuradio-core', exact=True) }}
        - lxml
        - menuinst  # [win]
        - pygobject
        - python
        - pyyaml
    test:
      commands:
        - grcc "$PREFIX/share/gnuradio/examples/metadata/file_metadata_vector_sink.grc"  # [not win]
        - python "%PREFIX%\\Library\\bin\\grcc.py" "%PREFIX%\\Library\\share\\gnuradio\\examples\\metadata\\file_metadata_vector_sink.grc"  # [win]
        - python file_metadata_vector_sink.py  # [not win]
        - if not exist %PREFIX%\\Scripts\\gnuradio-companion.exe exit 1  # [win]
        - if not exist %PREFIX%\\Scripts\\grcc.exe exit 1  # [win]
    about:
      home: https://gnuradio.org/
      doc_url: https://gnuradio.org/doc/doxygen/
      dev_url: https://github.com/gnuradio/gnuradio
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: GNU Radio Companion graphical flowgraph interface
  - name: gnuradio-qtgui
    build:
      skip: true  # [ppc64le or arm64]
      ignore_run_exports_from:
        # workaround to get host environment solved
        - openssl
    script: install_qtgui.sh  # [not win]
    script: install_qtgui.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        # conda-build needs native python to make .pyc files
        - python  # [build_platform != target_platform]
      host:
        - boost-cpp
        - {{ pin_subpackage('gnuradio-core', exact=True) }}
        - log4cpp
        # workaround to get host environment solved
        - openssl
        - pyqt
        - python
        - qt
        - qwt
        - volk
      run:
        - {{ pin_subpackage('gnuradio-core', exact=True) }}
        - pyqt
        - python
        - {{ pin_compatible('qwt', max_pin='x.x') }}
    test:
      imports:
        - gnuradio.qtgui
    about:
      home: https://gnuradio.org/
      doc_url: https://gnuradio.org/doc/doxygen/
      dev_url: https://github.com/gnuradio/gnuradio
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: GNU Radio QT module providing graphical components
  - name: gnuradio-soapy
    script: install_soapy.sh  # [not win]
    script: install_soapy.bat  # [win]
    build:
      ignore_run_exports_from:
        # workaround to get host environment solved
        - openssl
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        # conda-build needs native python to make .pyc files
        - python  # [build_platform != target_platform]
      host:
        - boost-cpp
        - {{ pin_subpackage('gnuradio-core', exact=True) }}
        - log4cpp
        # workaround to get host environment solved
        - openssl
        - python
        - soapysdr
      run:
        - {{ pin_subpackage('gnuradio-core', exact=True) }}
        - python
    test:
      imports:
        - gnuradio.soapy
    about:
      home: https://gnuradio.org/
      doc_url: https://gnuradio.org/doc/doxygen/
      dev_url: https://github.com/gnuradio/gnuradio
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: GNU Radio SoapySDR module for using a variety of SDR devices
      description: >
        This module provides GNU Radio source and sink blocks for a variety of
        SDR devices using SoapySDR, a generalized C/C++ library which provides
        abstraction in interfacing with different SDR devices and vendors.
  - name: gnuradio-uhd
    script: install_uhd.sh  # [not win]
    script: install_uhd.bat  # [win]
    build:
      entry_points:
        - uhd_siggen = gnuradio.uhd.uhd_siggen_base:main  # [win]
      ignore_run_exports_from:
        # workaround to get host environment solved
        - openssl
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        # conda-build needs native python to make .pyc files
        - python  # [build_platform != target_platform]
      host:
        - boost-cpp
        - {{ pin_subpackage('gnuradio-core', exact=True) }}
        - log4cpp
        # workaround to get host environment solved
        - openssl
        - python
        - uhd
      run:
        - boost-cpp
        - {{ pin_subpackage('gnuradio-core', exact=True) }}
        - python
    test:
      commands:
        - if not exist %PREFIX%\\Scripts\\uhd_siggen.exe exit 1  # [win]
      imports:
        - gnuradio.uhd
    about:
      home: https://gnuradio.org/
      doc_url: https://gnuradio.org/doc/doxygen/
      dev_url: https://github.com/gnuradio/gnuradio
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: GNU Radio UHD module for Ettus USRP radios
  - name: gnuradio-video-sdl
    script: install_video_sdl.sh  # [not win]
    script: install_video_sdl.bat  # [win]
    build:
      ignore_run_exports_from:
        # workaround to get host environment solved
        - openssl
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        # conda-build needs native python to make .pyc files
        - python  # [build_platform != target_platform]
      host:
        - boost-cpp
        - {{ pin_subpackage('gnuradio-core', exact=True) }}
        - log4cpp
        # workaround to get host environment solved
        - openssl
        - python
        - sdl
      run:
        - {{ pin_subpackage('gnuradio-core', exact=True) }}
        - python
    test:
      imports:
        - gnuradio.video_sdl
    about:
      home: https://gnuradio.org/
      doc_url: https://gnuradio.org/doc/doxygen/
      dev_url: https://github.com/gnuradio/gnuradio
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: GNU Radio SDL module providing video components
  - name: gnuradio-zeromq
    script: install_zeromq.sh  # [not win]
    script: install_zeromq.bat  # [win]
    build:
      ignore_run_exports_from:
        # workaround to get host environment solved
        - openssl
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        # conda-build needs native python to make .pyc files
        - python  # [build_platform != target_platform]
      host:
        - boost-cpp
        - cppzmq
        - {{ pin_subpackage('gnuradio-core', exact=True) }}
        - log4cpp
        # workaround to get host environment solved
        - openssl
        - python
        - zeromq
      run:
        - boost-cpp
        - {{ pin_subpackage('gnuradio-core', exact=True) }}
        - python
        - pyzmq
    test:
      imports:
        - gnuradio.zeromq
    about:
      home: https://gnuradio.org/
      doc_url: https://gnuradio.org/doc/doxygen/
      dev_url: https://github.com/gnuradio/gnuradio
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: GNU Radio ZeroMQ module for message passing functionality
  - name: gnuradio-build-deps
    build:
      string: {{ (pin_subpackage('gnuradio-core', exact=True) if (pin_subpackage('gnuradio-core', exact=True) is string) else '').partition(' ')[-1].partition(' ')[-1] }}
    requirements:
      host:
        # need to populate host to get complete build string (why?)
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ pin_subpackage('gnuradio-core', exact=True) }}
      run:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - cmake
        - ninja
        - numpy {{ numpy }}.*
        - pip  # [win]
        - pkg-config
        - pybind11
      run_constrained:
        - {{ pin_subpackage('gnuradio-core', exact=True) }}
    test:
      commands:
        - cmake --help
    about:
      home: https://gnuradio.org/
      doc_url: https://gnuradio.org/doc/doxygen/
      dev_url: https://github.com/gnuradio/gnuradio
      license: GPL-3.0-or-later
      license_family: GPL
      license_file: COPYING
      summary: Meta-package for GNU Radio deps used to manually build OOT modules
      description: >
        Install this meta-package into an environment with `gnuradio` or
        `gnuradio-core` in order to be able to build out-of-tree modules
        manually. DO NOT USE THIS IN CONDA RECIPES.
  # need an output with a script defined to work-around "empty" output detection
  # with python in both build (due to ninja) and host environments
  - name: gnuradio
    script: install_gnuradio.sh  # [not win]
    script: install_gnuradio.bat  # [win]

about:
  home: https://gnuradio.org/
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: The free and open software radio ecosystem
  description: >
    GNU Radio is a free software development toolkit that provides the signal
    processing runtime and processing blocks to implement software radios using
    readily-available, low-cost external RF hardware and commodity processors.
    It is widely used in hobbyist, academic and commercial environments to
    support wireless communications research as well as to implement real-world
    radio systems.

    GNU Radio applications are primarily written using the Python programming
    language, while the supplied, performance-critical signal processing path
    is implemented in C++ using processor floating point extensions where
    available. Thus, the developer is able to implement real-time, high-
    throughput radio systems in a simple-to-use, rapid-application-development
    environment.

  doc_url: https://gnuradio.org/doc/doxygen/
  dev_url: https://github.com/gnuradio/gnuradio

extra:
  recipe-maintainers:
    - ryanvolz
