azure:
  store_build_artifacts: true
bot:
  abi_migration_branches:
  - 3.8
  - 3.9
  automerge: true
build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
  osx_arm64: osx_64
build_with_mambabuild: true
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test_on_native_only: true
