azure: {store_build_artifacts: true}
bot:
  automerge: true
  abi_migration_branches:
   - 3.8
build_platform: {linux_aarch64: linux_64, linux_ppc64le: linux_64, osx_arm64: osx_64}
conda_forge_output_validation: true
test_on_native_only: true
